# -*- coding: utf-8 -*-
"""week2_personal_intro.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1apDvQKBJqr3DET7r_spv2GNpLu39A8VS

student grading system Program
"""

name=input("Enter your name:")
marks=int(input("Enter your marks:"))
if marks>=90:
  grade,message="A","Excellent work!!"
elif marks>=80:
  grade,message="B","good keep rocking!!"
elif marks>=70:
  grade,message="C","good but try your hardest"
elif marks>=60:
  grade, message="D","give your best"
else:
  grade,message="E","Don't Worry keep trying"
print(f"\n{name} your grade is {grade} and {message}")